menu:
    Archive: /archives/
    Photography: https://www.flickr.com/jacobthomason
    About: /about/

favicon: /favicon.ico
favicons: /favicon.icns
logo: /images/logo.png

# Comment
# e.g disqus: seansun
disqus: jacobt
duoshuo:

# Analytics
# google-analytics:
ga: UA-489149-6

# Copyright Infomation
startyear: 2013

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: true
